version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: atlas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: atlas_roads_test
      MYSQL_USER: jenkins
      MYSQL_PASSWORD: jenkins123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - atlas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nexus:
    image: sonatype/nexus3:latest
    container_name: atlas-nexus
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=273m
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - atlas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  atlas-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  nexus_data:
    driver: local

