version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: atlas-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: atlas_roads
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - atlas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    image: atlas-laravel:latest
    container_name: atlas-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_NAME: "Atlas Roads Library"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
      
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: atlas_roads
      DB_USERNAME: laravel
      DB_PASSWORD: laravel123
      
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - atlas-network
    depends_on:
      mysql:
        condition: service_healthy

  nexus:
    image: sonatype/nexus3:latest
    container_name: atlas-nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - atlas-network

volumes:
  mysql_data:
  nexus_data:

networks:
  atlas-network:
    driver: bridge
